import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  // Let n be the number of people
  // t = 360 / n
  // r = 250
  // x(t) = r cos(t)
  // y(t) = r sin(t)

  const interval = (number) => (2 * Math.PI) / number;

  const angles = (number) => {
    const array = Array.from(Array(number).keys()).map((index) => {
      return [index * interval(number), (index + 1) * interval(number)]
    });

    array[array.length - 1][1] = 0;
    return array;
  }

  const y = (t) => 250 * Math.cos(t);
  const x = (t) => 250 * Math.sin(t);
  const colors = ["#0074D9", "#FF4136", "#2ECC40", "#FF851B", "#7FDBFF", "#B10DC9", "#FFDC00", "#001f3f", "#39CCCC", "#01FF70", "#85144b", "#F012BE", "#3D9970", "#111111", "#AAAAAA"]
  const people = ['Ben', 'Jerry', 'Sam']

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <svg height="500" width="500">
          <defs>
            <clipPath id="circle">
              <circle cx="0" cy="0" r="240" />
            </clipPath>
          </defs>
          <g transform="matrix(1 0 0 -1 250 250)">
            <circle cx="0" cy="0" r="240" stroke="black" fill="white" />
            {angles(people.length).map((angle, index) => 
              <>
                <path 
                  key={index}
                  d={`M0 0 L${x(angle[0])} ${y(angle[0])} A250 250 0 0 0 ${x(angle[1])} ${y(angle[1])} Z`}
                  fill={colors[index]} clipPath="url(#circle)" />
              </>
            )}
          </g>
        </svg>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
